version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    healthcheck:
      test: [ "CMD", "php-fpm", "-t" ]
      interval: 10s
      timeout: 5s
      retries: 3
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      php:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "nginx", "-t" ]
      interval: 10s
      timeout: 5s
      retries: 3
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: task
      POSTGRES_USER: task
      POSTGRES_PASSWORD: 123
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U task" ]
      interval: 10s
      timeout: 5s
      retries: 5
  composer:
    image: composer:latest
    volumes:
      - .:/app
